{% set version = "1.5.5" %}
{% set sha256 = "167F972DC7F0B21E2C10138F5A8DDEEE0B446CC33935CE20905AE40356B682EC" %}

package:
  name: cyclus
  version: {{ version }}

source:
  fn: cyclus-{{ version }}-{{ sha256 }}.zip
  url: https://github.com/cyclus/cyclus/archive/ecc59260649705d72b4d9f5151911a0efbbd9202.zip
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win or osx or py<=27]
  detect_binary_files_with_prefix: true
  preserve_egg_dir: True
    
requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - coincbc
    - boost-cpp
    - libxmlpp-4.0
    - libxml2
    - liblapack
    - hdf5
    - glib
    - python-dev
    - jinja2
    - pandas
    - cython
    - pip
    - setuptools
  run:
    - python-dev
    - boost-cpp
    - coincbc
    - sqlite
    - hdf5
    - libxmlpp-4.0
    - libxml2
    - liblapack
    - glib
    - pandas
    - jinja2
    - pytables
    - pprintpp

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pytest
  source_files:
    - tests

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The agent-based fuel cycle simulator."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - katyhuff
    - FlanFlanagan
    - stompsjo
    - bennibbelink
