{% set version = "1.5.5" %}
{% set sha256 = "e6628c1e91378f22a5b395f8901248b8459fc6a0efdbed60ce368066a5a28525" %}

package:
  name: cyclus
  version: {{ version }}

source:
  fn: cyclus-{{ version }}-{{ sha256 }}.zip
  url: https://github.com/bennibbelink/cyclus/archive/refs/heads/pyinstall-cmake.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or osx or py<=27]
  detect_binary_files_with_prefix: true
  preserve_egg_dir: True
    
requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - coincbc
    - boost-cpp
    - libxmlpp-4.0
    - libxml2
    - liblapack
    - hdf5
    - sqlite
    - glib
    - python
    - pandas
    - jinja2
    - cython
    - pip
    - setuptools
  host:
    - coincbc
    - boost-cpp
    - libxmlpp-4.0
    - libxml2
    - liblapack
    - blis
    - hdf5
    - sqlite
    - glib
    - python
    - pandas
    - python
    - pprintpp
    - cython
  run:
    - coincbc
    - boost-cpp
    - libxmlpp-4.0
    - libxml2
    - liblapack
    - blis
    - hdf5
    - sqlite
    - glib
    - python
    - pandas
    - python
    - pprintpp

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pytest
    - pytables
  source_files:
    - tests
    - share/dbtypes.json

about:
  home: http://fuelcycle.org/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: "The agent-based fuel cycle simulator."

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - katyhuff
    - FlanFlanagan
    - stompsjo
